# Generated by Django 4.1.2 on 2022-11-13 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0002_remove_pedidoproducto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='blog_post',
            field=models.TextField(null=True),
        ),
    ]
