# Generated by Django 4.1.2 on 2022-11-13 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_pedidoproducto_author_alter_pedidoproducto_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='status',
        ),
    ]
