# Generated by Django 4.1.2 on 2022-11-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_remove_pedidoproducto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
