# Generated by Django 4.1.2 on 2022-11-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_pedidoproducto_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='status',
        ),
    ]
