# Generated by Django 4.1.2 on 2022-11-14 00:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_alter_pedidoproducto_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='resumen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='blog_post',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
