# Generated by Django 4.1.2 on 2022-11-14 01:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_remove_pedidoproducto_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='blog_post',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
