# Generated by Django 4.1.2 on 2022-12-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
