# Generated by Django 4.1.2 on 2022-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extensionusuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionusuario',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
